### ISSUE TITLE
ElasticSearch Settings

### ISSUE THREAD

**Issue by Globegitter** [taterbase/mongoosastic#117]
First of all, thank you for this great plugin it made elasitcsearch very accessible to implement on one of our sites.
I am just getting started with all that, but I am looking now at this blogpost: http://www.elasticsearch.org/blog/starts-with-phrase-matching/ and I wonder how to apply these settings via mongoosastic.
I can see in the readme how to apply mappings, but where can you set the first part?
If I get that working I could then add that to the readme.

Edit: This tutorial http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html
has similar settings.

**Comment by taterbase** [comment]
Setting analyzers upon mapping within Mongoose has been a desired functionality for a while (see #22), it has yet to be implemented. For now users must manually set things like this outside of Mongoose.

If you discover a great solution please feel free to send a pull request, this would be a great feature.

**Comment by cwagner22** [comment]
I also need this feature.

**Comment by antoineverger** [comment]
Hi @taterbase,

I was about to work on a first step to introduce the settings. What's your advice for contributing for that ? Do I do a pull-request after commiting on master branch ? Should do I proceed as described in the README : feature-branching from develop branch and then pull-request ? I tried this last approach but it seems that develop branch has its test failing and was not modified since april 2013. I'm waiting for your answer, Cheers,

Antoine
