### ISSUE TITLE
Using indices

### ISSUE THREAD

**Issue by marsanla** [taterbase/mongoosastic#124]
Hii!! i would like to know wehre i need to put the indeces to search in two index in my ES. i have this:

```
Product.search({
     query: {
              filtered: {
                  indices: {
                         indices: ['products', 'producers'],
                                query: {
                                    match: {
                                        tags: {
                                            query: req.params.name,
                                            operator: 'and'
                                        }
                                    }
                                },
                                // "no_match_query": {
                                //     "term": {
                                //         "tag": "kow"
                                //     }
                                // }
                    },
                    filter: {
                    term: {
                            verified: 1
                }
                 }
           }
      },
      from: (page - 1) * count,
      size: count,
}, ...., ...);
```

And i dont know how to start with this.

Thanks!

**Comment by tsturzl** [comment]
You're query is passed as is to elasticsearch. For your example you'll be querying the "Product" index that is bound by mongoosastic to your mongoose model. So you'll be querying with the specific index "Products", which isn't what you're trying to do. The problem is that mongoosastic sets your index for you based on the model its bound to so in your case you're querying the route "http://host:port/Product/_search" where are you need to call "http://host:port/_search" to specify multiple indices.

You can see here: https://github.com/jamescarr/mongoosastic/blob/master/lib/mongoosastic.js#L119
how the search function is implemented.

However, fear not. You can still use mongoosastic to keep your data in sync between ES and mongodb. Though you'll probably need to use an ElasticSearch client to execute this query, but this isn't difficult at all. You can use something simple like [elastical](https://github.com/ramv/node-elastical), which is what mongoosastic uses, you can even call ElasticSearch directly with REST calls. Elasticsearch clients don't have much overhead, in fact they don't hold a persistent connection because ElasticSearch API is purely http based.

If you don't want to break the convention that mongoosastic provides, issue a feature request.

**Comment by taterbase** [comment]
@tsturzl fantastic answer! @marsanla at this time the best way to accomplish something like is making two separate queries using the two models, or follow @tsturzl's advice and use a lower level driver to make queries.

**Comment by marsanla** [comment]
I add this to make it possible from the library.
#128
